language: ruby
sudo: false
cache:
  bundler: true
rbenv:
- 2.5.3
before_install:
- yes | gem update --system --force
- gem install bundler
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  app: sweater-weather-road
  on:
    repo: brian-greeson/sweater-weather
  run: rails db:migrate
  api_key:
    secure: OclUbkc4VkKKDhzm9Yt9Lrurevp4Tu2wINgtsiE6/7POvsOu2b8WwSBcp2fjpBj0U85dFv+vV7LwU7r8MX97XyuO96barr/J7Ho+/DyODaZd3xsihzVImarHsHd0xEbqTvDQnRqGFQih/l4ggvRUkfKD0OnOutXmCgFxuit//ebZ2W+Vm9C0dw116vN8BJR/13IdNJ64Io/CfH2w+sXwAUW/oY5XRb/dgNn71/GxN97tt8P+Sv+eZLnM3WzNRtOrVI5+bm5zHxcegygKrAUxbIxY0eY4nM2rw/dQht5TJ739GJFrWhNF7SSVd4kUunYcbUicVxpqwNs17zFqZ7YgThpKLU8nB/qUH5DxltHO9tTyPCL2GjZW7M4FMdX2mOM5GIkIbCI+dHZIcRrlI1jvJeHcLX8eou57nXYO1t3UGKcT9KTmiE40ht+XlPSEix7FMaJH+8qEL+z13y5uc7sm1sw/VbaxZhsRcspICFG5OXKmMLJBpuOqvAxwJ48FKFUfdyOw+cLDPpWDqxu05rIUMRMI3TO2RdrQSA99/hjT8ozgu19p6NmAU9q8AYUcOr7iQFqbCPq8b1z9/ljHwtdFV3nAUd6HjXi4HzZDWifDobJjnmW+3QRNDz/S+HeB/Z38yksTx9riD6uWj6UE8gXJKb2u66FXyHG4NPi9Ty7UI84=
